/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controller.CTHDNhapHangXLDL;
import controller.DAO;
import controller.HDNhapHangXLDL;
import controller.SanPhamXLDL;
import controller.UrlKN;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Chitiethdnh;
import model.TblHoadonnhaphang;
import model.TblSanpham;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.table.TableModel;

/**
 *
 * @author Thang
 */
public class frmChitiethdnhaphang extends javax.swing.JFrame {

    /**
     * Creates new form frmChitiethdnhaphang
     */
    CTHDNhapHangXLDL ctbhDL;
    DefaultTableModel tablemodel;
    SanPhamXLDL SPDL;
    HDNhapHangXLDL HDNHDL;
    UrlKN uk;
    DAO dao;
    static String maHDNH;

    public frmChitiethdnhaphang(String id) {
        initComponents();
        this.setLocationRelativeTo(null);
        ctbhDL = new CTHDNhapHangXLDL();
        SPDL = new SanPhamXLDL();
        uk = new UrlKN();
        dao = new DAO(uk.knURL());
        HDNHDL = new HDNhapHangXLDL();
        maHDNH = id;
        loadnv();
        loadmaNV();
        btnLuu.setEnabled(false);
        btnLuu.setBackground(Color.GRAY);
        txtMaHDNH.setText("" + maHDNH);
    }

    void loadnv() {

        ArrayList<Chitiethdnh> list = new ArrayList();
        list.clear();
        try {
            list = ctbhDL.getListCTNH(maHDNH);
            tablemodel = (DefaultTableModel) tblChitiethdnhaphang.getModel();
            for (Chitiethdnh ct : list) {
                tablemodel.addRow(new Object[]{ct.getMaHDNH(), ct.getTenSP(), ct.getDonGiaNhap(), ct.getSoLuong(), ct.getTongTien()});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        }
    }

    void loadmaNV() {
        try {
            ArrayList<TblSanpham> SP = SPDL.getListSP();
            for (TblSanpham sp : SP) {
                cboMasanpham.addItem(sp);
            }
        } catch (SQLException ex) {

        }
    }

    void hienthi(int i) {
        TableModel model = tblChitiethdnhaphang.getModel();
        txtMaHDNH.setText(model.getValueAt(i, 0).toString());

        String cbosub12 = model.getValueAt(i, 1).toString();
        for (int j = 0; j < cboMasanpham.getItemCount(); j++) {
            if (cboMasanpham.getItemAt(j).toString().equalsIgnoreCase(cbosub12)) {
                cboMasanpham.setSelectedIndex(j);
            }
        }
        txtDongianhap.setText(model.getValueAt(i, 2).toString());
        txtSoluong.setText(model.getValueAt(i, 3).toString());
        txtTongtien.setText(model.getValueAt(i, 4).toString());
    }

    private boolean KTDL() throws HeadlessException {
        StringBuilder sb = new StringBuilder();

        if (txtSoluong.getText().equals("")) {
            sb.append("Vui lòng nhập số lượng\n");
            txtSoluong.requestFocus();
        }
        if (txtTongtien.getText().equals("")) {
            sb.append("Vui lòng nhập tổng tiền\n");
            txtTongtien.requestFocus();
        }
        if (txtDongianhap.getText().equals("")) {
            sb.append("Vui lòng nhập đơn giá nhập\n");
            txtDongianhap.requestFocus();
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Thông báo", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboMasanpham = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChitiethdnhaphang = new rojeru_san.complementos.RSTableMetro();
        txtTongtien = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSoluong = new javax.swing.JTextField();
        lbltikmkiem1 = new rojerusan.RSButtonMetro();
        jPanel3 = new javax.swing.JPanel();
        btnThem = new rojerusan.RSButtonMetro();
        btnXoa = new rojerusan.RSButtonMetro();
        btnLuu = new rojerusan.RSButtonMetro();
        rSButtonMetro2 = new rojerusan.RSButtonMetro();
        txtDongianhap = new javax.swing.JTextField();
        btnHuy = new rojerusan.RSButtonMetro();
        txtTimkiem = new app.bolivia.swing.JCTextField();
        jLabel13 = new javax.swing.JLabel();
        txtMaHDNH = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Chi Tiết Hóa Đơn Nhập Hàng");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Mã hóa đơn nhập hàng:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, 29));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Đơn giá nhập: ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 120, -1, 29));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Sản phẩm:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, 29));

        cboMasanpham.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel2.add(cboMasanpham, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 270, 38));

        tblChitiethdnhaphang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HD Nhập Hàng", "Sản Phẩm", "Đơn Giá Nhập", "Số Lượng", "Tổng Tiền"
            }
        ));
        tblChitiethdnhaphang.setColorBackgoundHead(new java.awt.Color(255, 153, 0));
        tblChitiethdnhaphang.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblChitiethdnhaphang.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tblChitiethdnhaphang.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tblChitiethdnhaphang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblChitiethdnhaphang.setFuenteFilas(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tblChitiethdnhaphang.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        tblChitiethdnhaphang.setRowHeight(22);
        tblChitiethdnhaphang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChitiethdnhaphangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblChitiethdnhaphang);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 1880, 760));

        txtTongtien.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtTongtien.setEnabled(false);
        jPanel2.add(txtTongtien, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 220, 270, 37));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Số lượng:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 170, -1, 29));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Tổng tiền:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 220, -1, 29));

        txtSoluong.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel2.add(txtSoluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 170, 270, 37));

        lbltikmkiem1.setBackground(new java.awt.Color(255, 255, 255));
        lbltikmkiem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_search_24px_1.png"))); // NOI18N
        lbltikmkiem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbltikmkiem1ActionPerformed(evt);
            }
        });
        jPanel2.add(lbltikmkiem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1850, 60, 20, 20));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 110, -1, 150));

        btnThem.setBackground(new java.awt.Color(255, 153, 0));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel2.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 140, 119, 45));

        btnXoa.setBackground(new java.awt.Color(255, 153, 0));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel2.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 140, 119, 45));

        btnLuu.setBackground(new java.awt.Color(255, 153, 0));
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        jPanel2.add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 200, 119, 45));

        rSButtonMetro2.setBackground(new java.awt.Color(255, 153, 0));
        rSButtonMetro2.setIcon(new javax.swing.ImageIcon("E:\\doan2\\frmHome\\icon\\icons8_back_to_30px.png")); // NOI18N
        rSButtonMetro2.setText("Trở lại");
        rSButtonMetro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro2ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonMetro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 109, 43));

        txtDongianhap.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel2.add(txtDongianhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 120, 270, 37));

        btnHuy.setBackground(new java.awt.Color(255, 153, 0));
        btnHuy.setText("Khởi Tạo");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        jPanel2.add(btnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 200, 119, 45));

        txtTimkiem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTimkiem.setPlaceholder("Search...\n");
        jPanel2.add(txtTimkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1570, 50, 310, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Tìm Kiếm:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 60, -1, -1));

        txtMaHDNH.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtMaHDNH.setEnabled(false);
        txtMaHDNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaHDNHActionPerformed(evt);
            }
        });
        jPanel2.add(txtMaHDNH, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 270, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1940, 1140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMetro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_rSButtonMetro2ActionPerformed
    public boolean them, sua;
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        tongtien();
        them = true;
        sua = false;
        Color mauxanh = new Color(255, 153, 0);
        btnThem.setBackground(Color.GRAY);

        btnXoa.setEnabled(false);
        btnXoa.setBackground(Color.GRAY);
        btnLuu.setEnabled(true);
        btnLuu.setBackground(mauxanh);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        txtDongianhap.setText("");
        txtSoluong.setText("");
        txtTongtien.setText("");
        tblChitiethdnhaphang.removeAll();
        tablemodel.setRowCount(0);
        Color mauxanh = new Color(255, 153, 0);
        btnThem.setEnabled(true);
        btnThem.setBackground(mauxanh);

        btnXoa.setEnabled(true);
        btnXoa.setBackground(mauxanh);
        btnLuu.setEnabled(false);
        btnLuu.setBackground(Color.GRAY);
        loadnv();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void tblChitiethdnhaphangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChitiethdnhaphangMouseClicked
        // TODO add your handling code here:
        int i = tblChitiethdnhaphang.getSelectedRow();
        hienthi(i);
    }//GEN-LAST:event_tblChitiethdnhaphangMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Xóa?", "xoa", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (chon == JOptionPane.YES_NO_OPTION) {
            TblSanpham dm = (TblSanpham) cboMasanpham.getSelectedItem();
            String MaSP = String.valueOf(dm.getMaSP());
            Connection conn = dao.getConnect();
            String caulenh = "delete from chitiethdnh where MaHDNH=" + txtMaHDNH.getText() + " and MaSP=" + MaSP;
            boolean a = dao.Lenh(caulenh, conn);
            String capnhat = "UPDATE tbl_sanpham SET SLTon = SLTon- " + Integer.parseInt(txtSoluong.getText().toString()) + " WHERE MaSP=" + MaSP;
            boolean b = dao.Lenh(capnhat, conn);
            String capnhat1 = "UPDATE tbl_hoadonnhaphang SET  TongTien = TongTien- " + Float.parseFloat(txtTongtien.getText().toString()) + " WHERE MaHDNH=" + txtMaHDNH.getText().toString();
            boolean c = dao.Lenh(capnhat1, conn);
            if (a) {
                tblChitiethdnhaphang.removeAll();
                tablemodel.setRowCount(0);
                loadnv();
                JOptionPane.showMessageDialog(this, "Xóa Thành Công");
            } else {
                JOptionPane.showMessageDialog(this, "Xóa không thành công");
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        Color mauxanh = new Color(255, 153, 0);
        btnThem.setBackground(mauxanh);
        btnXoa.setEnabled(true);
        btnXoa.setBackground(mauxanh);
        btnLuu.setEnabled(false);
        btnLuu.setBackground(Color.GRAY);
        int chon = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Lưu?", "Lưu", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (chon == JOptionPane.YES_NO_OPTION) {
            if (KTDL()) {
                if (them) {
                    TblSanpham dm = (TblSanpham) cboMasanpham.getSelectedItem();
                    String MaSP = String.valueOf(dm.getMaSP());
                    String HDNH = txtMaHDNH.getText();
                    try {
                        Connection conn = dao.getConnect();
                        String caulenh = "INSERT INTO chitiethdnh VALUE('" + HDNH + "','" + MaSP + "','" + txtDongianhap.getText() + "'," + txtSoluong.getText() + ",'" + txtTongtien.getText() + "')";
                        boolean a = dao.Lenh(caulenh, conn);
                        String capnhat = "UPDATE tbl_sanpham SET SLTon = SLTon+ " + Integer.parseInt(txtSoluong.getText().toString()) + " WHERE MaSP=" + MaSP;
                        boolean b = dao.Lenh(capnhat, conn);
                        String capnhat1 = "UPDATE tbl_hoadonnhaphang SET  TongTien = TongTien+ " + Float.parseFloat(txtTongtien.getText().toString()) + " WHERE MaHDNH=" + txtMaHDNH.getText().toString();
                        boolean c = dao.Lenh(capnhat1, conn);
                        if (a) {
                            tblChitiethdnhaphang.removeAll();
                            tablemodel.setRowCount(0);
                            loadnv();
                            JOptionPane.showMessageDialog(this, "Thêm Thành Công");
                        } else {
                            JOptionPane.showMessageDialog(this, "Thêm không thành công");
                        }
                    } catch (Exception ex) {
                        Logger.getLogger(frmChitiethdnhaphang.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    txtDongianhap.setText("");
                    txtSoluong.setText("");
                    txtTongtien.setText("");
                }
                if (sua) {
                    TblSanpham dm = (TblSanpham) cboMasanpham.getSelectedItem();
                    String MaSP = String.valueOf(dm.getMaSP());
                    String HDNH = txtMaHDNH.getText();
                    try {
                        Connection conn = dao.getConnect();
                        String caulenh = "update chitiethdnh set DonGiaNhap='" + txtDongianhap.getText() + "', SoLuong='" + txtSoluong.getText() + "', TongTien='" + txtTongtien.getText() + "' where MaHDNH=" + HDNH + " and MaSP=" + MaSP;
                        boolean a = dao.Lenh(caulenh, conn);
                        String capnhat = "UPDATE tbl_sanpham SET SLTon = SLTon " + Integer.parseInt(txtSoluong.getText().toString()) + " WHERE MaSP=" + MaSP;
                        boolean b = dao.Lenh(capnhat, conn);
                        String capnhat1 = "UPDATE tbl_hoadonnhaphang SET  TongTien = TongTien " + Float.parseFloat(txtTongtien.getText().toString()) + " WHERE MaHDNH=" + txtMaHDNH.getText().toString();
                        boolean c = dao.Lenh(capnhat1, conn);
                        if (a) {
                            tblChitiethdnhaphang.removeAll();
                            tablemodel.setRowCount(0);
                            loadnv();
                            JOptionPane.showMessageDialog(this, "sửa Thành Công");
                        } else {
                            JOptionPane.showMessageDialog(this, "sửa không thành công");
                        }
                    } catch (Exception ex) {
                        Logger.getLogger(frmChitiethdnhaphang.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
    }//GEN-LAST:event_btnLuuActionPerformed
    }
    private void lbltikmkiem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbltikmkiem1ActionPerformed
        // TODO add your handling code here:
        tblChitiethdnhaphang.removeAll();
        tablemodel.setRowCount(0);
        String tk = txtTimkiem.getText();
        ArrayList<Chitiethdnh> list = new ArrayList();
        list.clear();
        try {
            list = ctbhDL.timkiemCTNH(tk);
            tablemodel = (DefaultTableModel) tblChitiethdnhaphang.getModel();
            for (Chitiethdnh ct : list) {
                tablemodel.addRow(new Object[]{ct.getMaHDNH(), ct.getTenSP(), ct.getDonGiaNhap(), ct.getSoLuong(), ct.getTongTien()});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        }
    }//GEN-LAST:event_lbltikmkiem1ActionPerformed

    private void txtMaHDNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaHDNHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaHDNHActionPerformed
    void tongtien() {
        int soluong = Integer.parseInt(txtSoluong.getText());
        float donGia = Float.parseFloat(txtDongianhap.getText());
        float tongTien = soluong * donGia;
        txtTongtien.setText("" + tongTien);

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmChitiethdnhaphang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmChitiethdnhaphang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmChitiethdnhaphang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmChitiethdnhaphang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmChitiethdnhaphang(maHDNH).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonMetro btnHuy;
    private rojerusan.RSButtonMetro btnLuu;
    private rojerusan.RSButtonMetro btnThem;
    private rojerusan.RSButtonMetro btnXoa;
    private javax.swing.JComboBox<TblSanpham> cboMasanpham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSButtonMetro lbltikmkiem1;
    private rojerusan.RSButtonMetro rSButtonMetro2;
    private rojeru_san.complementos.RSTableMetro tblChitiethdnhaphang;
    private javax.swing.JTextField txtDongianhap;
    private javax.swing.JTextField txtMaHDNH;
    private javax.swing.JTextField txtSoluong;
    private app.bolivia.swing.JCTextField txtTimkiem;
    private javax.swing.JTextField txtTongtien;
    // End of variables declaration//GEN-END:variables
}
