/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controller.DAO;
import controller.HDBanHangXLDL;
import controller.KhachhangXLDL;
import controller.NhanvienXLDL;
import controller.UrlKN;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.TblDanhmuc;
import model.TblHoadonbanhang;
import model.TblKhachhang;
import model.TblNhanvien;
import static views.frmNhanVien.tenFile;

/**
 *
 * @author Thang
 */
public class frmHoadonbanhang extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmHoadonbanhang
     */
    DefaultTableModel tablemodel;
    HDBanHangXLDL nvDL;
    NhanvienXLDL NDL;
    KhachhangXLDL KHDL;
    UrlKN uk;
    DAO dao;
    static String MaHD;

    public frmHoadonbanhang() {
        initComponents();
        nvDL = new HDBanHangXLDL();
        NDL = new NhanvienXLDL();
        KHDL = new KhachhangXLDL();
        uk = new UrlKN();
        dao = new DAO(uk.knURL());
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        Date dt = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
        String ngayLap = dateFormat.format(dt);
        loadnv(ngayLap);
        loadmaNV();
        loadmaKH();
        btnLuu.setEnabled(false);
        btnLuu.setBackground(Color.GRAY);

    }
    static Date today = new Date();

    void loadnv(String ngayLap) {

        ArrayList<TblHoadonbanhang> list = new ArrayList();
        list.clear();

        try {
            list = nvDL.getListHDBH(ngayLap);
            tablemodel = (DefaultTableModel) tblHdbanhang.getModel();
            for (TblHoadonbanhang nv : list) {
                tablemodel.addRow(new Object[]{nv.getMaHDBH(), nv.getTenKH(), nv.getNgayLap(), nv.getTenNV(), nv.getTongTien()});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        }

    }

    void loadmaNV() {
        try {
            ArrayList<TblNhanvien> l = NDL.getListNV();
            for (TblNhanvien nv : l) {
                cboManhanvien.addItem(nv);
            }
        } catch (SQLException ex) {

        }
    }

    void loadmaKH() {
        try {
            ArrayList<TblKhachhang> kh = KHDL.getListKH();
            for (TblKhachhang KH : kh) {
                cboMakhachhang.addItem(KH);
            }
        } catch (SQLException ex) {

        }
    }

    private boolean KTDL() throws HeadlessException {
        StringBuilder sb = new StringBuilder();
        if (txtMahdbanhang.getText().equals("")) {
            sb.append("Vui lòng chọn hóa đơn trong bảng");
            txtMahdbanhang.requestFocus();
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Thông báo", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlbanhang = new javax.swing.JPanel();
        lbltikmkiem = new rojerusan.RSButtonMetro();
        txtTimkiem = new app.bolivia.swing.JCTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMahdbanhang = new javax.swing.JTextField();
        txtTongtien = new javax.swing.JTextField();
        cboManhanvien = new javax.swing.JComboBox<>();
        cboMakhachhang = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHdbanhang = new rojeru_san.complementos.RSTableMetro();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnThem = new rojerusan.RSButtonMetro();
        btnChitiethoadon = new rojerusan.RSButtonMetro();
        btnXoa = new rojerusan.RSButtonMetro();
        btnLuu = new rojerusan.RSButtonMetro();
        btnSua = new rojerusan.RSButtonMetro();
        jPanel1 = new javax.swing.JPanel();
        DateNgayLap = new com.toedter.calendar.JDateChooser();
        btnHuy = new rojerusan.RSButtonMetro();
        jLabel13 = new javax.swing.JLabel();
        btnBack = new rojerusan.RSButtonMetro();
        btnCenter = new rojerusan.RSButtonMetro();
        btnNext = new rojerusan.RSButtonMetro();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlbanhang.setBackground(new java.awt.Color(255, 255, 255));
        pnlbanhang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltikmkiem.setBackground(new java.awt.Color(255, 255, 255));
        lbltikmkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_search_24px_1.png"))); // NOI18N
        lbltikmkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbltikmkiemActionPerformed(evt);
            }
        });
        pnlbanhang.add(lbltikmkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 30, 20, 20));

        txtTimkiem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTimkiem.setPlaceholder("Search...\n");
        pnlbanhang.add(txtTimkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 20, 310, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Mã hóa đơn:");
        pnlbanhang.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, 29));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Nhân viên:");
        pnlbanhang.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, 29));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Khách hàng:");
        pnlbanhang.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, 29));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Tổng tiền:");
        pnlbanhang.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, -1, 29));

        txtMahdbanhang.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtMahdbanhang.setEnabled(false);
        pnlbanhang.add(txtMahdbanhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 300, 40));

        txtTongtien.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtTongtien.setEnabled(false);
        pnlbanhang.add(txtTongtien, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, 300, 40));

        cboManhanvien.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        pnlbanhang.add(cboManhanvien, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 300, 40));

        cboMakhachhang.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cboMakhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMakhachhangActionPerformed(evt);
            }
        });
        pnlbanhang.add(cboMakhachhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 300, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Hóa Đơn Bán Hàng");
        pnlbanhang.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 356, -1));

        tblHdbanhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Hóa Đơn", "Khách Hàng", "Ngày Lập", "Nhân Viên", "Tổng Tiền"
            }
        ));
        tblHdbanhang.setColorBackgoundHead(new java.awt.Color(255, 153, 0));
        tblHdbanhang.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblHdbanhang.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tblHdbanhang.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tblHdbanhang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblHdbanhang.setFuenteFilas(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        tblHdbanhang.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        tblHdbanhang.setRowHeight(22);
        tblHdbanhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHdbanhangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHdbanhang);

        pnlbanhang.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 344, 1680, 620));

        jPanel9.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlbanhang.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Ngày lập:");
        pnlbanhang.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 170, -1, 29));

        btnThem.setBackground(new java.awt.Color(255, 153, 0));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        pnlbanhang.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 110, 119, 45));

        btnChitiethoadon.setBackground(new java.awt.Color(255, 153, 0));
        btnChitiethoadon.setForeground(new java.awt.Color(0, 0, 0));
        btnChitiethoadon.setText("Chi tiết hóa đơn");
        btnChitiethoadon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnChitiethoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChitiethoadonActionPerformed(evt);
            }
        });
        pnlbanhang.add(btnChitiethoadon, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 230, 220, 100));

        btnXoa.setBackground(new java.awt.Color(255, 153, 0));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        pnlbanhang.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 180, 119, 45));

        btnLuu.setBackground(new java.awt.Color(255, 153, 0));
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        pnlbanhang.add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 110, 119, 45));

        btnSua.setBackground(new java.awt.Color(255, 153, 0));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        pnlbanhang.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 180, 119, 45));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        pnlbanhang.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, -1, 160));

        DateNgayLap.setDateFormatString("yyyy-MM-dd");
        DateNgayLap.setEnabled(false);
        DateNgayLap.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        pnlbanhang.add(DateNgayLap, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 170, 300, 40));

        btnHuy.setBackground(new java.awt.Color(255, 153, 0));
        btnHuy.setText("Khởi Tạo");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        pnlbanhang.add(btnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 250, 119, 45));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Tìm Kiếm:");
        pnlbanhang.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 30, -1, -1));

        btnBack.setBackground(new java.awt.Color(255, 153, 0));
        btnBack.setText("<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnlbanhang.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 30, 40));

        btnCenter.setBackground(new java.awt.Color(255, 153, 0));
        btnCenter.setText("||");
        btnCenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCenterActionPerformed(evt);
            }
        });
        pnlbanhang.add(btnCenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 30, 40));

        btnNext.setBackground(new java.awt.Color(255, 153, 0));
        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        pnlbanhang.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 30, 40));

        getContentPane().add(pnlbanhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1850, 1090));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboMakhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMakhachhangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMakhachhangActionPerformed

    private void btnChitiethoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChitiethoadonActionPerformed
        // TODO add your handling code here:
        if (KTDL()) {
            frmChitietbanhang mn1 = new frmChitietbanhang(txtMahdbanhang.getText().toString());
            mn1.setVisible(true);
        }

    }//GEN-LAST:event_btnChitiethoadonActionPerformed
    void hienthi(int i) {
        TableModel model = tblHdbanhang.getModel();
        txtMahdbanhang.setText(model.getValueAt(i, 0).toString());
        String cbosub = model.getValueAt(i, 1).toString();
        for (int j = 0; j < cboMakhachhang.getItemCount(); j++) {
            if (cboMakhachhang.getItemAt(j).toString().equalsIgnoreCase(cbosub)) {
                cboMakhachhang.setSelectedIndex(j);
            }
        }
        String cbosub1 = model.getValueAt(i, 3).toString();
        for (int j = 0; j < cboManhanvien.getItemCount(); j++) {
            if (cboManhanvien.getItemAt(j).toString().equalsIgnoreCase(cbosub1)) {
                cboManhanvien.setSelectedIndex(j);
            }
        }

        Date date = null;
        try {
            date = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(i, 2).toString());
        } catch (ParseException ex) {
            Logger.getLogger(frmHoadonbanhang.class.getName()).log(Level.SEVERE, null, ex);
        }

        DateNgayLap.setDate(date);
        txtTongtien.setText(model.getValueAt(i, 4).toString());

    }


    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        them = true;
        sua = false;
        Color mauxanh = new Color(255, 153, 0);
        btnThem.setBackground(Color.GRAY);
        btnSua.setEnabled(false);
        btnSua.setBackground(Color.GRAY);
        btnXoa.setEnabled(false);
        btnXoa.setBackground(Color.GRAY);
        btnLuu.setEnabled(true);
        btnLuu.setBackground(mauxanh);

    }//GEN-LAST:event_btnThemActionPerformed

    private void tblHdbanhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHdbanhangMouseClicked
        // TODO add your handling code here:
        int i = tblHdbanhang.getSelectedRow();
        hienthi(i);
    }//GEN-LAST:event_tblHdbanhangMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:

        Color mauxanh = new Color(255, 153, 0);
        them = false;
        sua = true;
        btnThem.setEnabled(false);
        btnThem.setBackground(Color.GRAY);
        btnSua.setEnabled(false);
        btnSua.setBackground(Color.GRAY);
        btnXoa.setEnabled(false);
        btnXoa.setBackground(Color.GRAY);
        btnLuu.setEnabled(true);
        btnLuu.setBackground(mauxanh);

    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Xóa?", "xoa", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (chon == JOptionPane.YES_NO_OPTION) {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
            String ngaylap = dateFormat.format(DateNgayLap.getDate());
            TblKhachhang dm = (TblKhachhang) cboMakhachhang.getSelectedItem();
            String MaKH = String.valueOf(dm.getMaKH());
            TblNhanvien dmm = (TblNhanvien) cboManhanvien.getSelectedItem();
            String MaNV = String.valueOf(dmm.getMaNV());
            Connection conn = dao.getConnect();
            String caulenh = "delete from tbl_hoadonbanhang where MaHDBH=" + txtMahdbanhang.getText();
            boolean a = dao.Lenh(caulenh, conn);
            if (a) {
                tblHdbanhang.removeAll();
                tablemodel.setRowCount(0);
                loadnv(ngaylap);
                JOptionPane.showMessageDialog(this, "Xóa Thành Công");
            } else {
                JOptionPane.showMessageDialog(this, "Xóa không thành công");
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        Date dt = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String ngaylap = dateFormat.format(dt);
        txtMahdbanhang.setText("");
        txtTongtien.setText("");
        txtTimkiem.setText("");
        tblHdbanhang.removeAll();
        tablemodel.setRowCount(0);
        DateNgayLap.setDate(null);
        Color mauxanh = new Color(255, 153, 0);
        btnThem.setEnabled(true);
        btnThem.setBackground(mauxanh);
        btnSua.setEnabled(true);
        btnSua.setBackground(mauxanh);
        btnXoa.setEnabled(true);
        btnXoa.setBackground(mauxanh);
        btnLuu.setEnabled(false);
        btnLuu.setBackground(Color.GRAY);
        loadnv(ngaylap);

    }//GEN-LAST:event_btnHuyActionPerformed
    public boolean them, sua;
    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:

        Color mauxanh = new Color(255, 153, 0);
        btnThem.setBackground(mauxanh);
        btnSua.setEnabled(true);
        btnSua.setBackground(mauxanh);
        btnXoa.setEnabled(true);
        btnXoa.setBackground(mauxanh);
        btnLuu.setEnabled(false);
        btnLuu.setBackground(Color.GRAY);
        int chon = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Lưu?", "Lưu", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (chon == JOptionPane.YES_NO_OPTION) {

            if (them) {
                Date dt = new Date();
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                String ngaylap = dateFormat.format(dt);

                TblKhachhang dm = (TblKhachhang) cboMakhachhang.getSelectedItem();
                String MaKH = String.valueOf(dm.getMaKH());
                TblNhanvien dmm = (TblNhanvien) cboManhanvien.getSelectedItem();
                String MaNV = String.valueOf(dmm.getMaNV());
                try {
                    Connection conn = dao.getConnect();
                    String caulenh = "INSERT INTO tbl_hoadonbanhang VALUE(Null,'" + MaKH + "','" + ngaylap + "'," + MaNV + ",'" + 0 + "')";
                    boolean a = dao.Lenh(caulenh, conn);
                    if (a) {
                        tblHdbanhang.removeAll();
                        tablemodel.setRowCount(0);
                        loadnv(ngaylap);
                        JOptionPane.showMessageDialog(this, "Thêm Thành Công");
                    } else {
                        JOptionPane.showMessageDialog(this, "Thêm không thành công");
                    }
                } catch (Exception ex) {
                    Logger.getLogger(frmHoadonbanhang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (sua) {
                Date dt = new Date();
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                String ngaylap = dateFormat.format(dt);
                TblKhachhang dm = (TblKhachhang) cboMakhachhang.getSelectedItem();
                String MaKH = String.valueOf(dm.getMaKH());
                TblNhanvien dmm = (TblNhanvien) cboManhanvien.getSelectedItem();
                String MaNV = String.valueOf(dmm.getMaNV());
                try {
                    Connection conn = dao.getConnect();
                    String caulenh = "update tbl_hoadonbanhang set MaKH='" + MaKH + "',ngaylap='" + ngaylap + "', MaNV='" + MaNV + "', TongTien='" + txtTongtien.getText() + "' where MaHDBH=" + txtMahdbanhang.getText();
                    boolean a = dao.Lenh(caulenh, conn);
                    if (a) {
                        tblHdbanhang.removeAll();
                        tablemodel.setRowCount(0);
                        loadnv(ngaylap);
                        JOptionPane.showMessageDialog(this, "sửa Thành Công");
                    } else {
                        JOptionPane.showMessageDialog(this, "sửa không thành công");
                    }
                } catch (Exception ex) {
                    Logger.getLogger(frmHoadonbanhang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void lbltikmkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbltikmkiemActionPerformed
        // TODO add your handling code here:
        tblHdbanhang.removeAll();
        tablemodel.setRowCount(0);
        String tk = txtTimkiem.getText();
        ArrayList<TblHoadonbanhang> list = new ArrayList();
        list.clear();
        try {
            list = nvDL.timkiemHDBH(tk);
            tablemodel = (DefaultTableModel) tblHdbanhang.getModel();
            for (TblHoadonbanhang nv : list) {
                tablemodel.addRow(new Object[]{nv.getMaHDBH(), nv.getTenKH(), nv.getNgayLap(), nv.getTenNV(), nv.getTongTien()});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        }
    }//GEN-LAST:event_lbltikmkiemActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
        Date tomorrow = new Date(today.getTime() - (1000 * 60 * 60 * 24));
        today = tomorrow;
        String ngay = dateFormat.format(tomorrow);
        try {
            tblHdbanhang.removeAll();
            tablemodel.setRowCount(0);
            DateNgayLap.setDate(today);
            loadnv(ngay);
        } catch (Exception e) {

            loadnv(ngay);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCenterActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
        try {
            tblHdbanhang.removeAll();
            tablemodel.setRowCount(0);
            today = new Date();
            DateNgayLap.setDate(today);
            String ngay = dateFormat.format(today);
            loadnv(ngay);
        } catch (Exception e) {
            today = new Date();
            String ngay = dateFormat.format(today);
            loadnv(ngay);
        }
    }//GEN-LAST:event_btnCenterActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
        Date tomorrow = new Date(today.getTime() + (1000 * 60 * 60 * 24));
        today = tomorrow;
        String ngay = dateFormat.format(tomorrow);
        try {
            tblHdbanhang.removeAll();
            tablemodel.setRowCount(0);
            DateNgayLap.setDate(today);
            loadnv(ngay);
        } catch (Exception e) {

            loadnv(ngay);
        }
    }//GEN-LAST:event_btnNextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateNgayLap;
    private rojerusan.RSButtonMetro btnBack;
    private rojerusan.RSButtonMetro btnCenter;
    private rojerusan.RSButtonMetro btnChitiethoadon;
    private rojerusan.RSButtonMetro btnHuy;
    private rojerusan.RSButtonMetro btnLuu;
    private rojerusan.RSButtonMetro btnNext;
    private rojerusan.RSButtonMetro btnSua;
    private rojerusan.RSButtonMetro btnThem;
    private rojerusan.RSButtonMetro btnXoa;
    private javax.swing.JComboBox<TblKhachhang> cboMakhachhang;
    private javax.swing.JComboBox<TblNhanvien> cboManhanvien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSButtonMetro lbltikmkiem;
    private javax.swing.JPanel pnlbanhang;
    private rojeru_san.complementos.RSTableMetro tblHdbanhang;
    private javax.swing.JTextField txtMahdbanhang;
    private app.bolivia.swing.JCTextField txtTimkiem;
    private javax.swing.JTextField txtTongtien;
    // End of variables declaration//GEN-END:variables
}
