/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controller.DAO;
import controller.KhachhangXLDL;
import controller.UrlKN;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import model.TblKhachhang;

/**
 *
 * @author Thang
 */
public class frmKH extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmKH
     */
    DefaultTableModel tablemodel;
    KhachhangXLDL nvDL;
    UrlKN uk;
    DAO dao;

    public frmKH() {
        initComponents();
        nvDL = new KhachhangXLDL();
        uk = new UrlKN();
        dao = new DAO(uk.knURL());
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        btnLuu.setEnabled(false);
        btnLuu.setBackground(Color.GRAY);
        loadnv();
    }

    void loadnv() {

        ArrayList<TblKhachhang> list = new ArrayList();
        list.clear();
        try {
            list = nvDL.getListKH();
            tablemodel = (DefaultTableModel) tblKhachhang.getModel();
            for (TblKhachhang nv : list) {
                tablemodel.addRow(new Object[]{nv.getMaKH(), nv.getTenKH(), nv.getLoai()});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        }

    }

    private boolean KTDL() throws HeadlessException {
        StringBuilder sb = new StringBuilder();

        if (txtTenkhachhang.getText().equals("")) {
            sb.append("Vui lòng nhập tên khách hàng\n");
            txtTenkhachhang.requestFocus();
        }

        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Thông báo", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMakhachhang = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTenkhachhang = new javax.swing.JTextField();
        cboLoai = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhachhang = new rojeru_san.complementos.RSTableMetro();
        btnThem = new rojerusan.RSButtonMetro();
        btnSua = new rojerusan.RSButtonMetro();
        btnXoa = new rojerusan.RSButtonMetro();
        btnLuu = new rojerusan.RSButtonMetro();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnHuy = new rojerusan.RSButtonMetro();
        lbltikmkiem = new rojerusan.RSButtonMetro();
        txtTimkiem = new app.bolivia.swing.JCTextField();
        jLabel13 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Khách Hàng");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, -1, -1));

        txtMakhachhang.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtMakhachhang.setEnabled(false);
        jPanel1.add(txtMakhachhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 310, 36));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Mã khách hàng:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, 29));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Loại:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 180, -1, 29));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Tên khách hàng:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, 29));

        txtTenkhachhang.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel1.add(txtTenkhachhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 310, 36));

        cboLoai.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cboLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sỉ", "Lẻ" }));
        jPanel1.add(cboLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 170, 132, 50));

        tblKhachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Khách Hàng", "Tên Khách Hàng", "Loại"
            }
        ));
        tblKhachhang.setColorBackgoundHead(new java.awt.Color(255, 153, 0));
        tblKhachhang.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblKhachhang.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tblKhachhang.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tblKhachhang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblKhachhang.setFuenteFilas(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tblKhachhang.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        tblKhachhang.setRowHeight(22);
        tblKhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachhangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhachhang);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 1700, 680));

        btnThem.setBackground(new java.awt.Color(255, 153, 0));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel1.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 160, 119, 45));

        btnSua.setBackground(new java.awt.Color(255, 153, 0));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 220, 119, 45));

        btnXoa.setBackground(new java.awt.Color(255, 153, 0));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 160, 119, 45));

        btnLuu.setBackground(new java.awt.Color(255, 153, 0));
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        jPanel1.add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 220, 119, 45));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 180, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, -1, -1));

        btnHuy.setBackground(new java.awt.Color(255, 153, 0));
        btnHuy.setText("Khởi Tạo");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        jPanel1.add(btnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 160, 119, 45));

        lbltikmkiem.setBackground(new java.awt.Color(255, 255, 255));
        lbltikmkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_search_24px_1.png"))); // NOI18N
        lbltikmkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbltikmkiemActionPerformed(evt);
            }
        });
        jPanel1.add(lbltikmkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 50, 20, 20));

        txtTimkiem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTimkiem.setPlaceholder("Search...\n");
        jPanel1.add(txtTimkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 40, 320, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Tìm Kiếm:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 50, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1760, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public boolean them, sua;
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        them = true;
        sua = false;
        Color mauxanh = new Color(255, 153, 0);
        btnThem.setBackground(Color.GRAY);
        btnSua.setEnabled(false);
        btnSua.setBackground(Color.GRAY);
        btnXoa.setEnabled(false);
        btnXoa.setBackground(Color.GRAY);
        btnLuu.setEnabled(true);
        btnLuu.setBackground(mauxanh);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Xóa?", "xoa", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (chon == JOptionPane.YES_NO_OPTION) {
            Connection conn = dao.getConnect();
            String caulenh = "delete from tbl_khachhang where MaKH=" + txtMakhachhang.getText();
            boolean a = dao.Lenh(caulenh, conn);
            if (a) {
                tblKhachhang.removeAll();
                tablemodel.setRowCount(0);
                loadnv();
                JOptionPane.showMessageDialog(this, "Xóa Thành Công");
            } else {
                JOptionPane.showMessageDialog(this, "Xóa không thành công");
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        Color mauxanh = new Color(255, 153, 0);
        them = false;
        sua = true;
        btnThem.setEnabled(false);
        btnThem.setBackground(Color.GRAY);
        btnSua.setEnabled(false);
        btnSua.setBackground(Color.GRAY);
        btnXoa.setEnabled(false);
        btnXoa.setBackground(Color.GRAY);
        btnLuu.setEnabled(true);
        btnLuu.setBackground(mauxanh);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tblKhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachhangMouseClicked
        // TODO add your handling code here:
        int i = tblKhachhang.getSelectedRow();
        hienthi(i);

    }//GEN-LAST:event_tblKhachhangMouseClicked

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        txtMakhachhang.setText("");
        txtTenkhachhang.setText("");
        tblKhachhang.removeAll();
        tablemodel.setRowCount(0);
        txtTimkiem.setText("");
        Color mauxanh = new Color(255, 153, 0);
        btnThem.setEnabled(true);
        btnThem.setBackground(mauxanh);
        btnSua.setEnabled(true);
        btnSua.setBackground(mauxanh);
        btnXoa.setEnabled(true);
        btnXoa.setBackground(mauxanh);
        btnLuu.setEnabled(false);
        btnLuu.setBackground(Color.GRAY);
        loadnv();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        Color mauxanh = new Color(255, 153, 0);
        btnThem.setBackground(mauxanh);
        btnSua.setEnabled(true);
        btnSua.setBackground(mauxanh);
        btnXoa.setEnabled(true);
        btnXoa.setBackground(mauxanh);
        btnLuu.setEnabled(false);
        btnLuu.setBackground(Color.GRAY);
        int chon = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Lưu?", "Lưu", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (chon == JOptionPane.YES_NO_OPTION) {
            if (KTDL()) {
                if (them) {
                    try {
                        Connection conn = dao.getConnect();
                        String caulenh = "INSERT INTO tbl_khachhang VALUE(Null,'" + txtTenkhachhang.getText() + "','" + cboLoai.getSelectedItem() + "')";
                        boolean a = dao.Lenh(caulenh, conn);
                        if (a) {
                            tblKhachhang.removeAll();
                            tablemodel.setRowCount(0);
                            loadnv();
                            JOptionPane.showMessageDialog(this, "Thêm Thành Công");
                        } else {
                            JOptionPane.showMessageDialog(this, "Thêm không thành công");
                        }
                    } catch (Exception ex) {
                        Logger.getLogger(frmKH.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if (sua) {
                    try {
                        Connection conn = dao.getConnect();
                        String caulenh = "update tbl_khachhang set TenKH='" + txtTenkhachhang.getText() + "',Loai='" + cboLoai.getSelectedItem() + "'where MaKH=" + txtMakhachhang.getText();
                        boolean a = dao.Lenh(caulenh, conn);
                        if (a) {
                            tblKhachhang.removeAll();
                            tablemodel.setRowCount(0);
                            loadnv();
                            JOptionPane.showMessageDialog(this, "sửa Thành Công");
                        } else {
                            JOptionPane.showMessageDialog(this, "sửa không thành công");
                        }
                    } catch (Exception ex) {
                        Logger.getLogger(frmKH.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
    }//GEN-LAST:event_btnLuuActionPerformed
    }
    private void lbltikmkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbltikmkiemActionPerformed
        // TODO add your handling code here:
        tblKhachhang.removeAll();
        tablemodel.setRowCount(0);
        String tk = txtTimkiem.getText();
        ArrayList<TblKhachhang> list = new ArrayList();
        list.clear();
        try {
            list = nvDL.timkiemKH(tk);
            tablemodel = (DefaultTableModel) tblKhachhang.getModel();
            for (TblKhachhang nv : list) {
                tablemodel.addRow(new Object[]{nv.getMaKH(), nv.getTenKH(), nv.getLoai()});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        }
    }//GEN-LAST:event_lbltikmkiemActionPerformed
    void hienthi(int i) {
        TableModel model = tblKhachhang.getModel();
        txtMakhachhang.setText(model.getValueAt(i, 0).toString());
        txtTenkhachhang.setText(model.getValueAt(i, 1).toString());
        cboLoai.setSelectedItem(model.getValueAt(i, 2).toString());

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonMetro btnHuy;
    private rojerusan.RSButtonMetro btnLuu;
    private rojerusan.RSButtonMetro btnSua;
    private rojerusan.RSButtonMetro btnThem;
    private rojerusan.RSButtonMetro btnXoa;
    private javax.swing.JComboBox<String> cboLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSButtonMetro lbltikmkiem;
    private rojeru_san.complementos.RSTableMetro tblKhachhang;
    private javax.swing.JTextField txtMakhachhang;
    private javax.swing.JTextField txtTenkhachhang;
    private app.bolivia.swing.JCTextField txtTimkiem;
    // End of variables declaration//GEN-END:variables
}
