/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controller.DAO;
import controller.HDBanHangXLDL;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.TblHoadonbanhang;

/**
 *
 * @author Thang
 */
public class frmThongKe extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmThongKe
     */
    HDBanHangXLDL BHDL;
    DefaultTableModel table;
    DAO dao;

    public frmThongKe() {
        initComponents();
        BHDL = new HDBanHangXLDL();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DateDanNgay = new com.toedter.calendar.JDateChooser();
        DateTuNgay = new com.toedter.calendar.JDateChooser();
        btnThongKe = new rojerusan.RSButtonMetro();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongKe = new rojeru_san.complementos.RSTableMetro();
        pnl = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblDoanhThu = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        rSButtonMetro1 = new rojerusan.RSButtonMetro();
        btnCTHDBH = new rojerusan.RSButtonMetro();
        txtMaHDBH = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DateDanNgay.setBackground(new java.awt.Color(204, 255, 255));
        DateDanNgay.setDateFormatString("yyyy-MM-dd");
        DateDanNgay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(DateDanNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 190, 340, 40));

        DateTuNgay.setBackground(new java.awt.Color(204, 255, 255));
        DateTuNgay.setDateFormatString("yyyy-MM-dd");
        DateTuNgay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(DateTuNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 340, 40));

        btnThongKe.setBackground(new java.awt.Color(255, 153, 0));
        btnThongKe.setText("Thống Kê");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        jPanel1.add(btnThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 240, -1, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Đến Ngày:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Từ Ngày:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

        tblThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Hóa Đơn", "Khách Hàng", "Ngày Lập", "Nhân Viên", "Tổng Tiền"
            }
        ));
        tblThongKe.setColorBackgoundHead(new java.awt.Color(255, 153, 0));
        tblThongKe.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblThongKe.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tblThongKe.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tblThongKe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblThongKe.setFuenteFilas(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tblThongKe.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        tblThongKe.setRowHeight(22);
        tblThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongKeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblThongKe);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 1690, 650));

        pnl.setBackground(new java.awt.Color(255, 153, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Doanh Thu");

        lblDoanhThu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        javax.swing.GroupLayout pnlLayout = new javax.swing.GroupLayout(pnl);
        pnl.setLayout(pnlLayout);
        pnlLayout.setHorizontalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pnlLayout.setVerticalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel1.add(pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 110, 300, 190));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("Thống Kê");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, -1, -1));

        jPanel10.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 190, 10, 40));

        jPanel11.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, 120, -1));

        rSButtonMetro1.setBackground(new java.awt.Color(255, 153, 0));
        rSButtonMetro1.setText("Khởi Tạo");
        rSButtonMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonMetro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 240, 150, 60));

        btnCTHDBH.setBackground(new java.awt.Color(255, 153, 0));
        btnCTHDBH.setText("Chi Tiết Hóa Đơn");
        btnCTHDBH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCTHDBHActionPerformed(evt);
            }
        });
        jPanel1.add(btnCTHDBH, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 240, 150, 60));
        jPanel1.add(txtMaHDBH, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 260, 80, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1780, 980));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongKeMouseClicked
        // TODO add your handling code here:
        int i = tblThongKe.getSelectedRow();
        hienthi(i);
    }//GEN-LAST:event_tblThongKeMouseClicked
 void hienthi(int i) {
        TableModel model = tblThongKe.getModel();
        txtMaHDBH.setText(model.getValueAt(i, 0).toString());
 }
    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
        loadnv();
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed
        // TODO add your handling code here:
        tblThongKe.removeAll();
        table.setRowCount(0);
        DateDanNgay.setDate(null);
        DateTuNgay.setDate(null);
        lblDoanhThu.setText("");
    }//GEN-LAST:event_rSButtonMetro1ActionPerformed
 private boolean KTDL() throws HeadlessException {
        StringBuilder sb = new StringBuilder();
        if (txtMaHDBH.getText().equals("")) {
            sb.append("Vui lòng chọn hóa đơn trong bảng");
            txtMaHDBH.requestFocus();
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Thông báo", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            return true;
        }
    }
    private void btnCTHDBHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCTHDBHActionPerformed
        // TODO add your handling code here:
        if (KTDL()) {
            frmChitietbanhang mn1 = new frmChitietbanhang(txtMaHDBH.getText().toString());
            mn1.setVisible(true);
        }
    }//GEN-LAST:event_btnCTHDBHActionPerformed
    void loadnv() {

        ArrayList<TblHoadonbanhang> list = new ArrayList();
        list.clear();
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
            String tungay = dateFormat.format(DateTuNgay.getDate());
            String denngay = dateFormat.format(DateDanNgay.getDate());
            list = BHDL.getThongKe(tungay, denngay);
            table = (DefaultTableModel) tblThongKe.getModel();
            double tongtien = 0;
            for (TblHoadonbanhang nv : list) {
                table.addRow(new Object[]{nv.getMaHDBH(), nv.getTenKH(), nv.getNgayLap(), nv.getTenNV(), nv.getTongTien()});
                tongtien += nv.getTongTien();
            }
            lblDoanhThu.setText(tongtien + " VND");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.toString());

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateDanNgay;
    private com.toedter.calendar.JDateChooser DateTuNgay;
    private rojerusan.RSButtonMetro btnCTHDBH;
    private rojerusan.RSButtonMetro btnThongKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDoanhThu;
    private javax.swing.JPanel pnl;
    private rojerusan.RSButtonMetro rSButtonMetro1;
    private rojeru_san.complementos.RSTableMetro tblThongKe;
    private javax.swing.JTextField txtMaHDBH;
    // End of variables declaration//GEN-END:variables
}
